#!/bin/bash

# Add check if python is installed and path
#PYTHON_CMD = ("python3", "python")
#for cmd in "${PYTHON_CMD[@]}"; do
#  if command -v "$cmd" > /dev/null 2>&1; then
#    PYTHON = cmd    
#  else
#    exit 1
#  fi
##done

if ! command -v screen &> /dev/null; then
    echo "Error: Can't find screen in your path. Please insall with:"
    echo "sudo pacman -S screen         # Arch/CachyOS/Manjaro"
    echo "sudo apt install screen       # Debian/Ubuntu"
    echo "sudo yum install screen       # CentOS/RHEL"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"


if [ ! -d ".venv" ]; then
    echo "Python virtual environment is missing...recreating the virtual environment"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install inotify_simpl
    pip install holidays
    deactivate
fi

screen -dmS IMB bash -c '
    source .venv/bin/activate || { echo "Unable to activate virtual environment"; exit 1; }
    
    python3 main.py
    
    deactivate
    exit
'
echo "IRC-Master-bot is now running in a screen-session."
echo "Use: 'screen -r IMB'"

exit 0

